global using ABulkCopy.ASqlServer.Column.ColumnTypes;
global using ABulkCopy.Common;
global using ABulkCopy.Common.Types.Column;
global using ABulkCopy.Common.Types.Table;
global using ABulkCopy.Common.Writer;
global using FluentAssertions;
global using Serilog;
global using System.IO.Abstractions.TestingHelpers;
global using Testing.Shared;
global using Testing.Shared.SqlServer;
global using Xunit;
global using SchemaTableTuple = (string schemaName, string tableName);