namespace Postgres.Tests.SystemTables.ColumnInfo;

[Collection(nameof(DatabaseCollection))]
public class PgTestJsonbColumn : PgTestBase
{
    private readonly IIdentifier _identifier;
    public PgTestJsonbColumn(DatabaseFixture dbFixture, ITestOutputHelper output)
        : base(dbFixture, output)
    {
        _identifier = GetIdentifier();
    }

    [Fact]
    public async Task TestGetColumnInfo_When_Jsonb()
    {
        // Arrange
        var tableName = GetName();
        await DropTableAsync(DatabaseFixture.DefaultSchemaName, tableName);
        await ExecuteNonQueryAsync(
            CreateTableWithColumn(DatabaseFixture.DefaultSchemaName, tableName, "jsonb"));
        var tableHeader = await PgSystemTables.GetTableHeaderAsync(
            DatabaseFixture.DefaultSchemaName, tableName, CancellationToken.None);
        tableHeader.Should().NotBeNull();

        // Act
        var columnInfo = (await PgSystemTables.GetTableColumnInfoAsync(
            tableHeader!, CancellationToken.None)).ToList();

        // Assert
        columnInfo.Count.Should().Be(2);
        var jsonbColumn = columnInfo[1];
        jsonbColumn.Should().BeOfType<PostgresJsonb>();
        jsonbColumn.Type.Should().Be(PgTypes.Jsonb);
        jsonbColumn.GetTypeClause().Should().Be(PgTypes.Jsonb);
        jsonbColumn.IsNullable.Should().BeTrue();
        jsonbColumn.GetDotNetType().Should().Be<string>();
    }

    [Fact]
    public async Task TestSerialize_Jsonb_IsNormalizedByPostgres()
    {
        // Arrange: column reads the value Postgres returns, which for jsonb is the
        // normalized form (duplicate keys removed, keys reordered, whitespace stripped).
        var column = new PostgresJsonb(1, "col1", isNullable: true);

        // Act: ask Postgres for the stored jsonb text of a messy literal.
        var stored = (string)(await DbFixture.PgRawCommand.ExecuteScalarAsync(
            "select '{\"b\": 1,  \"a\": 2, \"a\": 3}'::jsonb::text", CancellationToken.None))!;

        // Assert: jsonb dedups (a=3 wins) and reorders keys, unlike json which preserves text.
        stored.Should().Be("{\"a\": 3, \"b\": 1}");
        column.ToString(stored).Should().Be("'{\"a\": 3, \"b\": 1}'");
    }

    private string CreateTableWithColumn(
        string schemaName, string tableName, string columnType)
    {
        var sb = new StringBuilder();
        sb.Append("CREATE TABLE ");
        sb.Append(_identifier.Get(schemaName));
        sb.Append('.');
        sb.Append(_identifier.Get(tableName));
        sb.AppendLine(" (");
        sb.Append("    ").Append(_identifier.Get("Id")).AppendLine(" BIGINT GENERATED BY DEFAULT AS IDENTITY,");
        sb.Append("    ").Append(_identifier.Get("col1")).Append(' ').Append(columnType).AppendLine();
        sb.AppendLine(");");
        return sb.ToString();
    }
}
