namespace Postgres.Tests.SystemTables.ColumnInfo;

[Collection(nameof(DatabaseCollection))]
public class PgTestJsonColumn : PgTestBase
{
    private readonly IIdentifier _identifier;
    public PgTestJsonColumn(DatabaseFixture dbFixture, ITestOutputHelper output)
        : base(dbFixture, output)
    {
        _identifier = GetIdentifier();
    }

    [Theory]
    [InlineData("json", PgTypes.Json)]
    [InlineData("jsonb", PgTypes.Jsonb)]
    public async Task TestGetColumnInfo_When_Json(string columnType, string expectedType)
    {
        // Arrange
        var tableName = GetName();
        await DropTableAsync(DatabaseFixture.DefaultSchemaName, tableName);
        await ExecuteNonQueryAsync(
            CreateTableWithJsonColumn(DatabaseFixture.DefaultSchemaName, tableName, columnType));
        var tableHeader = await PgSystemTables.GetTableHeaderAsync(
            DatabaseFixture.DefaultSchemaName, tableName, CancellationToken.None);
        tableHeader.Should().NotBeNull();

        // Act
        var columnInfo = (await PgSystemTables.GetTableColumnInfoAsync(
            tableHeader!, CancellationToken.None)).ToList();

        // Assert
        columnInfo.Count.Should().Be(2);
        var jsonColumn = columnInfo[1];
        jsonColumn.Type.Should().Be(expectedType);
        jsonColumn.GetTypeClause().Should().Be(expectedType);
        jsonColumn.IsNullable.Should().BeTrue();
        jsonColumn.GetDotNetType().Should().Be<string>();
        jsonColumn.ToString("{\"a\": 1}").Should().Be("'{\"a\": 1}'");
    }

    private string CreateTableWithJsonColumn(
        string schemaName, string tableName, string columnType)
    {
        var sb = new StringBuilder();
        sb.Append("CREATE TABLE ");
        sb.Append(_identifier.Get(schemaName));
        sb.Append('.');
        sb.Append(_identifier.Get(tableName));
        sb.AppendLine(" (");
        sb.Append("    ").Append(_identifier.Get("Id")).AppendLine(" BIGINT GENERATED BY DEFAULT AS IDENTITY,");
        sb.Append("    ").Append(_identifier.Get("col1")).Append(' ').Append(columnType).AppendLine();
        sb.AppendLine(");");
        return sb.ToString();
    }
}
