name: Build Console application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout all
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build src/ABulkCopy.sln --no-restore

    - name: Publish
      run: dotnet publish -c Release

