name: Build Console application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  slnFile: 'src/ABulkCopy.sln'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout all
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Build
      run: dotnet build ${{env.slnFile}}

    - name: Publish
      run: dotnet publish ${{env.slnFile}} -c Release

