name: Build Console application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  slnFile: 'src/ABulkCopy.sln'
  consoleProjFile: 'src/ABulkCopy.Cmd/ABulkCopy.Cmd.csproj'
  commonTest: 'src/Common.Test/Common.Test.csproj'
  asqlserverTest: 'src/ASqlServer.Test/ASqlServer.Test.csproj'
  apostgresTest: 'src/APostgres.Test/APostgres.Test.csproj'
  aparserTest: 'src/AParser.Test/AParser.Test.csproj'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout all
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'

    - name: Build
      run: dotnet build ${{env.slnFile}}

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        overrideConfig: |
          update-build-number=false
          next-version=0.1.1
        updateAssemblyInfo: true
        useConfigFile: true

    - name: Publish
      run: dotnet publish ${{env.consoleProjFile}} -c Release

    - name: Upload program artifact
      uses: actions/upload-artifact@v4
      with:
        name: program
        path: ./src/ABulkCopy.Cmd/bin/Release/net8.0/win-x64/publish

    - name: Upload tests artifact
      uses: actions/upload-artifact@v4
      with:
        name: tests
        path: |
          ./src/AParser.Test/bin/Debug/net8.0
          ./src/APostgres.Test/bin/Debug/net8.0
          ./src/ASqlServer.Test/bin/Debug/net8.0
          ./src/Common.Test/bin/Debug/net8.0
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: tests

    - name: Test AParser
      run: dotnet test ./AParser.Test/bin/Debug/net8.0/AParser.Test.dll -v m
    
    - name: Test Common
      run: dotnet test ./Common.Test/bin/Debug/net8.0/Common.Test.dll -v m 

    - name: Test ASqlServer
      run: dotnet test ./ASqlServer.Test/bin/Debug/net8.0/ASqlServer.Test.dll -v m -e AppSettings__ConnectionString="${{secrets.MSS_ABULKCOPY_TEST_CONNECTIONSTRING}}"


    
