name: Build Console application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  slnFile: 'src/ABulkCopy.sln'
  consoleProjFile: 'src/ABulkCopy.Cmd/ABulkCopy.Cmd.csproj'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout all
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build ${{env.slnFile}}

    - name: Publish
      run: dotnet publish ${{env.consoleProjFile}} -c Release

